# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:year/:month/:title/
#relative_permalinks: true

# Setup
title:            Fernando Bevilacqua
tagline:          'Senior software engineer and open-source contributor'
description:      'Fernando Bevilacqua is a senior software engineer, former game developer (now enthusiast during the free time), passionate about everything open-source.'
url:              https://www.fernandobevilacqua.com
baseurl:          /
redirect:         false

author:
  name:           'Fernando Bevilacqua'
  url:            https://twitter.com/as3gamegears

paginate:         5
paginate_path:    "page:num"

gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
