# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:year/:month/:title/
#relative_permalinks: true

# Setup
title:            Fernando Bevilacqua
tagline:          'Professor of Computer Science and indie game developer'
description:      'Fernando Bevilacqua is a Professor of Computer Science and indie game developer.'
url:              http://www.fernandobevilacqua.com
baseurl:          /
redirect:         true

author:
  name:           'Fernando Bevilacqua'
  url:            https://twitter.com/as3gamegears

paginate:         5
paginate_path:    "page:num"

gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
