# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Fernando Bevilacqua
tagline:          ''
description:      'Professor of Computer Science and indie game developer.'
url:              https://fernandobevilacqua.com
baseurl:          /

author:
  name:           'Fernando Bevilacqua'
  url:            https://twitter.com/as3gamegears

paginate:         5
paginate_path:    "page:num"

gems:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
